### ISSUE TITLE
Errata: At-most-once guarantees for StatefulSets

### ISSUE THREAD

**Issue by embano1** [k8spatterns/examples#13]
Page 95 in the printed book, last paragraph:

> "When a node fails, it schedules new Pods on a different node unless Kubernetes can confirm that the Pods (and maybe the whole node) are shut down."

I think, corresponding with the "at most once" guarantee of stateful sets described in the chapter, this should read:

"When a node fails, it **does not** schedule new Pods on a different node unless Kubernetes can confirm that the Pods (and maybe the whole node) are shut down."

**Comment by rhuss** [comment]
Thanks a lot, I just fixed this in the source and should be available soon in the next electronic release (and sorry for the delay)
