### ISSUE TITLE
Health Probe: http://localhost:8080/toogle-live endpoint does not work

### ISSUE THREAD

**Issue by lautou** [k8spatterns/examples#22]
```
$ curl -s http://localhost:8080/toogle-live
Handling connection for 8080
{"timestamp":"2023-01-12T11:57:58.043+0000","status":404,"error":"Not Found","message":"No message available","path":"/toogle-live"}
```
same isse for toogle-ready:
```
$ curl http://localhost:8080/toogle-ready
{"timestamp":"2023-01-12T12:03:56.413+0000","status":404,"error":"Not Found","message":"No message available","path":"/toogle-ready"}
```

**Comment by rhuss** [comment]
Thanks for the heads up! Which image exactly have you used in this example ?

FYI, we will check all examples over the next weeks, and new examples will be added for the second edition of the book that comes out in May, including 5 new patterns.

**Comment by andresmmujica** [comment]
It seems file /opt/random-generator-ready is missing from published images and that's why the message.  I'll open a new issue.

**Comment by rhuss** [comment]
Please see #51 the marker file is now generated in `/tmp` so that the process can also now run as non-root.

**Comment by rhuss** [comment]
@lautou it is `curl -s http://localhost:8080/toggle-live`, not `curl -s http://localhost:8080/toogle-live`
