### ISSUE TITLE
Problems running PredictableDemands on Macbook Pro M2

### ISSUE THREAD

**Issue by sw564** [k8spatterns/examples#38]
I ran into a number of issues getting the foundational/PredictableDemands working.

1) The random-generator application didn't work with the Mac architecture.  I had to perform a multi-architecture build with buildx and then host the image in my own DockerHub account, which meant that I then had to update all of the images in the yml files to refer to my image.

This is what worked for me though there are probably other ways to solve this.  You may need to support other architectures.

docker buildx create --use
docker buildx build --platform linux/amd64,linux/arm64 --push -t <my dockerhub account>/random-generator:1.0 .

2) On the Mac I could not use hostPaths that start at the root as Mac now has the root path as read-only.  So I had to create a separate host path and then change the hostPath in yml files from /example, /logs, etc. to my hostpath.

3) The generator application was returning a 500 server error with both pod.yml and deployment.yml.  After some research I added the following spec above the app spec in deployment.yml and then it started to work.  I think that it started working as a side effect as I was unable to properly debug the issue.  Root cause is still a mystery to me.

spec:
  containers:
  - command:
    - "tail"
    - "-f"
    - "/dev/null"

**Comment by rhuss** [comment]
Thanks for the feedback! Indeed it looks like the image is only available for `linux/arm64/v8` (as I have build it on my Mac, but forgot to cross-build). That will be fixed asap.

The other issue, is interesting as I have tested it just recently with minikube v1.29.0 on macOS with Docker without any issue. 

But you are right, it's much safer to not write into the root file system. I will fix that asap and let you know.

Thanks for the feedback!

**Comment by sw564** [comment]
root being read-only was introduced with Catalina.  there is a way to change the root from read-only to read-write, but it doesn't seem appropriate.

also, when i inserted the buildx command i included a placeholder for the account name using angle brackets, but it looks like github decided to sanitize my message and remove it.  this is just a fyi in case someone comes across this post.

**Comment by rhuss** [comment]
Actually, I've run the test with minikube, which leverages a virtual machine that does not have this issue (see e.g. `minikube ssh sudo touch /x` works without issue. You can also jump into it and check out interactively). But still, it's not good practice to pollute the root filesystem space, so I'll change this).

Will provide multi-arch images asap, and then continue on the remaining example for the second edition of the book (that's the reason why everything is a bit in-flux).

Thanks for the help!

**Comment by sw564** [comment]
That didn't work for me.  Although I didn't get an error message, it didn't
create the directory.  I would have been surprised if it did.

x in ~
% minikube start
😄  minikube v1.29.0 on Darwin 13.2.1 (arm64)
✨  Using the qemu2 driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing qemu2 VM for "minikube" ...
🐳  Preparing Kubernetes v1.26.1 on Docker 20.10.23 ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
💡  Some dashboard features require the metrics-server addon. To enable all
features please run:

minikube addons enable metrics-server


🔎  Verifying ingress addon...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: dashboard, ingress, default-storageclass,
storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default"
namespace by default
xx in ~
% minikube ssh sudo touch /x
xx in ~
% ls -lag /x
ls: /x: No such file or directory
xx in ~
%

**Comment by rhuss** [comment]
Yeah, the difference is that I'm using the "docker" driver (not the "qemu2" driver). The "docker" driver starts a real virtual machine, whereas the "qemu2" driver integrates in the host OS (therefore the error). 

For the future, I will try both approaches. Thanks for the update!

**Comment by rhuss** [comment]
@sw564 Everything should also be fixed for the `qemu2` driver. Images have been updated for arm64 and amd64, and the temporary directories have been moved.

I also updated the section in `INSTALL.adoc` to highlight the difference between `docker` and `qemu2` on macOS. With `qemu2`, some of the networking-related examples could not work as expected. 

Please let me know if this works for you, I'm closing this issue for now. Feel free to reopne it in case or another issue for, well, another issue ;)

Enjoy and thanks again!

**Comment by sw564** [comment]
it worked with the docker driver.  minikube config setdriver docker

however, i had to use a simple minikube start.  this did not work: minikube start --mount --mount-string="$(pwd)/logs:/tmp/example" --memory 2G

also, the deployment.yml didn't work after deleting the pv-and-pvc.  i had to add it back.

**Comment by rhuss** [comment]
Sorry to hear that, that's strange. I tested it end-to-end with a qemu2 driver on an M1 Mac, so it should be very close to your setup. Can you try with a fresh minikube install (`minikube delete` and then start) and post the error that you see?

**Comment by sw564** [comment]
the instructions for running the pod.yml worked.

deployment.yml launched a deployment but i wasn't able to access it the same way.

```
...
)
kubectl patch deploy random-generator --type=json -p $patch
deployment.apps/random-generator patched
xx in ~/dev/kubernetes/examples on main
% 

% 
xx in ~/dev/kubernetes/examples on main
% kubectl logs -l app=random-generator -f | grep "=== "
xx in ~/dev/kubernetes/examples on main
% kubectl get deployments                                                                    
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
random-generator   1/1     1            1           2m47s
xx in ~/dev/kubernetes/examples on main
% POD_IP=$(kubectl get pod -l app=random-generator -o jsonpath='{.items[0].status.podIP}')            
xx in ~/dev/kubernetes/examples on main
% kubectl run -itq --rm --image=k8spatterns/curl-jq --restart=Never curl -- http://$POD_IP:8080 | jq .
parse error: Invalid numeric literal at line 1, column 5
pod default/curl terminated (Error)
xx in ~/dev/kubernetes/examples on main
%
```

**Comment by rhuss** [comment]
Sorry for being late again. If you are still on it, I would check first the value of `POD_IP` (e.g. `echo $POD_IP`) and then just leave out the `| jq .` to get to the real error message.

I rechecked everything and it "works for me" ™️ .

**Comment by andresmmujica** [comment]
@rhuss Hey, it seems you pushed only the arm64 image for 1.0. it'd be awesome if you push amd64 image as well.  Thank you.

**Comment by rhuss** [comment]
Sorry, my bad. It should be fixed now (and sorry for the delay)
